In [1]:
import os
import json
import pandas as pd

from dotenv import load_dotenv
from google.oauth2 import service_account
from google.cloud import storage

In [2]:
# Load environment variables from .env file
load_dotenv()

# Access the variables using os.getenv()
service_account_key = os.getenv("GCP_SERVICE_ACCOUNT_KEY")
project_id = os.getenv("GCP_PROJECT_ID")
bucket_name = os.getenv("GCP_BUCKET_NAME")

In [3]:
file_name = "2026-10-07_10-25-34_crime-data.json"

In [4]:
credentials = service_account.Credentials.from_service_account_file(service_account_key)
# Create a client to bundle configuration needed for API requests.
client = storage.Client(project=project_id,
                        credentials=credentials)
# Access a bucket 
bucket = client.bucket(bucket_name)
# Access an object (blob) in a bucket
file = bucket.blob(file_name)
# Download
content = json.loads(file.download_as_string())

In [5]:
df = pd.DataFrame(content)
df.head()

,report_period,report_year,report_month,district,section,category,same_month_prior_year,current_month,previous_month,ytd_prior_year,ytd_current,source_url,scraped_at
0,2026-08,2026,8,CITYWIDE,part1_violent,homicide,1,0,0,15,16,https://www.sanfranciscopolice.org/sites/defau...,2026-10-07T17:25:29+00:00
1,2026-08,2026,8,CITYWIDE,part1_violent,rape,21,16,17,155,138,https://www.sanfranciscopolice.org/sites/defau...,2026-10-07T17:25:29+00:00
2,2026-08,2026,8,CITYWIDE,part1_violent,robbery,157,134,114,1126,930,https://www.sanfranciscopolice.org/sites/defau...,2026-10-07T17:25:29+00:00
3,2026-08,2026,8,CITYWIDE,part1_violent,aggravated_assault,180,180,181,1420,1403,https://www.sanfranciscopolice.org/sites/defau...,2026-10-07T17:25:29+00:00
4,2026-08,2026,8,CITYWIDE,part1_violent,human_trafficking_sex_act,3,2,2,18,16,https://www.sanfranciscopolice.org/sites/defau...,2026-10-07T17:25:29+00:00

In [6]:
df["report_year"].value_counts()

report_year
2026    297
Name: count, dtype: int64

In [9]:
df["report_month"].value_counts()

report_month
8    297
Name: count, dtype: int64

In [ ]:
df["distri"].value_counts()

district
CITYWIDE      27
CENTRAL       27
SOUTHERN      27
BAYVIEW       27
MISSION       27
NORTHERN      27
PARK          27
RICHMOND      27
INGLESIDE     27
TARAVAL       27
TENDERLOIN    27
Name: count, dtype: int64

In [8]:
df.info()
display(df.describe())
display(df["district"].value_counts())
display(df["section"].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   report_period          297 non-null    object
 1   report_year            297 non-null    int64
 2   report_month           297 non-null    int64
 3   district               297 non-null    object
 4   section                297 non-null    object
 5   category               297 non-null    object
 6   same_month_prior_year  297 non-null    int64
 7   current_month          297 non-null    int64
 8   previous_month         297 non-null    int64
 9   ytd_prior_year         297 non-null    int64
 10  ytd_current            297 non-null    int64
 11  source_url             297 non-null    object
 12  scraped_at             297 non-null    object
dtypes: int64(7), object(6)
memory usage: 30.3+ KB

,report_year,report_month,same_month_prior_year,current_month,previous_month,ytd_prior_year,ytd_current
count,297.0,297.0,297.000000,297.000000,297.000000,297.000000,297.000000
mean,2026.0,8.0,69.340067,53.774411,58.494949,520.821549,439.363636
std,0.0,0.0,235.663158,177.660395,198.297434,1760.812017,1454.745286
min,2026.0,8.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.0,8.0,1.000000,0.000000,0.000000,6.000000,4.000000
50%,2026.0,8.0,10.000000,8.000000,8.000000,70.000000,65.000000
75%,2026.0,8.0,39.000000,35.000000,34.000000,322.000000,269.000000
max,2026.0,8.0,2576.000000,1965.000000,2142.000000,19328.000000,15938.000000

district
CITYWIDE      27
CENTRAL       27
SOUTHERN      27
BAYVIEW       27
MISSION       27
NORTHERN      27
PARK          27
RICHMOND      27
INGLESIDE     27
TARAVAL       27
TENDERLOIN    27
Name: count, dtype: int64

section
part1_violent        77
part1_property       77
domestic_violence    66
firearm              55
part1_total          11
other                11
Name: count, dtype: int64